### PR TITLE
feat: Adding a better destroy animation

### PR DESCRIPTION
**Pull request by edwardribas**
### Adding a better destroy animation and rearranging the CSS code.

- Made a improvement in the destroy animation of the toast
- Rearranged the CSS code without changing its logic

### CODE REVIEW

**Comment by 2nthony** [comment]
Thanks, looks good, but I notice something weird, basically the 4th toast.

pr build:

https://github.com/2nthony/vercel-toast/assets/19513289/756e29d0-5be5-4e28-ab6e-a4126cb4c988

the prod build, the 4th fade-out:

https://github.com/2nthony/vercel-toast/assets/19513289/bad48d14-811e-4add-8c3a-38def01eaed9

**Comment by edwardribas** [comment]
Oh, I didn't notice it! I'll try to fix it! Thanks for the feedback

**Comment by edwardribas** [comment]
@2nthony fixed! :)

**Comment by 2nthony** [comment]
thanks for the commit, but I found another issue, i recommended just add the destroy animate in this pr, revert the CSS rearanged.

steps: action + cancel, action, action + cancel
issue: toast size, if click `undo` in the 2nd toast, if won't do sort toasts. in prod is normal.

image

**Comment by edwardribas** [comment]
Sorry! The error was in my code logic. I let the sort function outside the timeout function, so it was trying to sort the elements before they were removed.

**Comment by 2nthony** [comment]
another similar issue

steps: action, action + cancel, action + cancel

image

**Comment by edwardribas** [comment]
@2nthony done!

**Comment by 2nthony** [comment]
Thanks but i still found another issue and somethings

### things

in the version release best practice, a feature/bug release should NOT include any code refactor, it is for avoid the potential issues like above.
so revert the css rearranged in this pr, SURE WELCOME you create another to do refactor!

### issue

steps: action + cancel, action

FYI: prod build is normal.

image

**Comment by edwardribas** [comment]
@2nthony made! I just removed the CSS rearrange and let only the remove animation in JS.

**Pull request merged**
